### ISSUE TITLE
Twice as many beans as the parameter "count"

### ISSUE THREAD

**Issue by witek1902** [musketyr/lusk#3]
If I run with parameter `-c500` Lusk generates 1000 beans, not 500.

**Comment by musketyr** [comment]
thanks for letting me know! I'll try to fix it when I have a bit of time

**Comment by musketyr** [comment]
just wonder, how do you count them? also for which framework.

**Comment by witek1902** [comment]
I counted Java files and later I used with BeanCounter.

**Comment by musketyr** [comment]
there should be exactly `count` number of class ending `Bean` and the same number of controllers ending `Controllers`. but as controllers are also beans then you will see twice a much beans. if this is the situation, I would say this is more question of explaining this in the docs.

**Comment by witek1902** [comment]
This is the situation.
Controller is also bean, so if I want generate "1000" beans, I don't need 1000 `*Bean` class, but 1000 beans (500 `*Bean` & 500 `*Controller`).
What do you think?

**Comment by musketyr** [comment]
I've changed the wording a bit to be more clear. sadly this was a one time project for demonstration purposes and I can't spend much more time on this.
